name: chaos
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alsa-lib=1.2.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - atk-1.0=2.36.0
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=4.1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cachetools=5.0.0
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.0.4
  - colorama=0.4.4
  - convertdate=2.4.0
  - cryptography=36.0.1
  - cycler=0.11.0
  - darts=0.2
  - dbus=1.13.6
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.7
  - ffmpeg=4.3.2
  - flit-core=3.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.96
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - frozenlist=1.3.0
  - fsspec=2022.2.0
  - future=0.18.2
  - gdk-pixbuf=2.42.6
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.6
  - graphite2=1.3.13
  - graphviz=3.0.0
  - grpcio=1.44.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=3.4.0
  - hijri-converter=2.2.3
  - holidays=0.13
  - icu=69.1
  - idna=3.3
  - importlib-metadata=4.11.2
  - importlib_metadata=4.11.2
  - importlib_resources=5.4.0
  - ipykernel=6.9.1
  - ipython=8.1.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.1.2
  - jupyter_console=6.4.3
  - jupyter_core=4.9.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.2
  - keyutils=1.6.1
  - kiwisolver=1.3.2
  - korean_lunar_calendar=0.2.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.1
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgd=2.3.3
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libllvm13=13.0.1
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.2
  - libprotobuf=3.19.4
  - librsvg=2.52.5
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.11
  - lightgbm=3.3.2
  - llvm-openmp=13.0.1
  - llvmlite=0.34.0
  - lz4-c=1.9.3
  - markdown=3.3.6
  - markupsafe=2.1.0
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2022.0.1
  - multidict=6.0.2
  - munkres=1.1.4
  - mysql-common=8.0.28
  - mysql-libs=8.0.28
  - nbclient=0.5.12
  - nbconvert=6.4.2
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.4
  - nettle=3.6
  - nfoursid=1.0.0
  - ninja=1.10.2
  - notebook=6.4.8
  - nspr=4.32
  - nss=3.74
  - numba=0.51.2
  - numpy=1.22.3
  - oauthlib=3.2.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.4.1
  - pandoc=2.17.1.1
  - pandocfilters=1.5.0
  - pango=1.50.5
  - parso=0.8.3
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=22.0.4
  - pixman=0.40.0
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.27
  - prompt_toolkit=3.0.27
  - protobuf=3.19.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.3.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.10.2
  - pytorch-lightning=1.5.10
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.12.9
  - qtconsole=5.2.2
  - qtconsole-base=5.2.2
  - qtpy=2.0.1
  - readline=8.1
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - send2trash=1.8.0
  - setuptools=59.5.0
  - six=1.16.0
  - sktime=0.10.1
  - sleef=3.5.1
  - sqlite=3.37.0
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - tbb=2021.5.0
  - tensorboard=2.8.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorboardx=2.5
  - terminado=0.13.3
  - testpath=0.6.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - torchmetrics=0.7.2
  - torchvision=0.11.3
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - u8darts=0.17.1
  - u8darts-torch=0.17.1
  - unicodedata2=14.0.0
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - wrapt=1.13.3
  - x264=1!161.3030
  - xarray=2022.3.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - backpack-for-pytorch==1.5.0
    - boltons==21.0.0
    - cmdstanpy==0.9.68
    - cython==0.29.28
    - docker-pycreds==0.4.0
    - dysts==0.1
    - einops==0.4.1
    - ephem==4.1.3
    - fonttools==4.30.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - json-tricks==3.15.5
    - lunarcalendar==0.0.9
    - pastel==0.2.1
    - pathtools==0.1.2
    - poethepoet==0.10.0
    - promise==2.3
    - psutil==5.9.0
    - pydeprecate==0.3.1
    - pymeeus==0.5.11
    - pystan==2.19.1.1
    - seaborn==0.11.2
    - sentry-sdk==1.5.7
    - setproctitle==1.2.2
    - setuptools-git==1.2
    - shortuuid==1.0.8
    - sklearn==0.0
    - smmap==5.0.0
    - termcolor==1.1.0
    - tomlkit==0.10.0
    - torchcde==0.2.5
    - torchdiffeq==0.2.2
    - torchdyn==1.0.1
    - torchsde==0.2.5
    - trampoline==0.1.2
    - ujson==5.1.0
    - wandb==0.12.14
    - yaspin==2.1.0
