name: chaos
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alsa-lib=1.2.6.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - blas=2.114
  - blas-devel=3.9.0
  - bleach=5.0.0
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.5.18.1
  - cachetools=5.0.0
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.1.3
  - colorama=0.4.4
  - cryptography=37.0.2
  - cudatoolkit=10.2.89
  - cycler=0.11.0
  - dbus=1.13.6
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.8
  - flit-core=3.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.33.3
  - freetype=2.10.4
  - frozenlist=1.3.0
  - fsspec=2022.5.0
  - future=0.18.2
  - gettext=0.19.8.1
  - giflib=5.2.1
  - google-auth=2.6.6
  - google-auth-oauthlib=0.4.6
  - grpcio=1.46.3
  - gst-plugins-base=1.20.2
  - gstreamer=1.20.2
  - icu=69.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_resources=5.7.1
  - ipykernel=6.13.0
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.5.1
  - jupyter=1.0.0
  - jupyter_client=7.3.1
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=1.1.0
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.1
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.70.2
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm13=13.0.1
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.3
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libstdcxx-ng=12.1.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libuv=1.43.0
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - markdown=3.3.7
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2022.0.1
  - mkl-devel=2022.0.1
  - mkl-include=2022.0.1
  - multidict=6.0.2
  - munkres=1.1.4
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - nbclient=0.6.3
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - notebook=6.4.11
  - nspr=4.32
  - nss=3.78
  - numpy=1.22.4
  - oauthlib=3.2.0
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - packaging=21.3
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.1.1
  - pip=22.1.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.29
  - prompt_toolkit=3.0.29
  - protobuf=3.20.1
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydeprecate=0.3.2
  - pygments=2.12.0
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.9
  - pytorch=1.11.0
  - pytorch-lightning=1.6.3
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=23.0.0
  - qt=5.12.9
  - qtconsole=5.3.0
  - qtconsole-base=5.3.0
  - qtpy=2.1.0
  - readline=8.1
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - send2trash=1.8.0
  - setuptools=59.5.0
  - six=1.16.0
  - soupsieve=2.3.1
  - sqlite=3.38.5
  - stack_data=0.2.0
  - tbb=2021.5.0
  - tensorboard=2.9.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - terminado=0.15.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - torchmetrics=0.8.2
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.2.1.post0
  - typing-extensions=4.2.0
  - typing_extensions=4.2.0
  - tzdata=2022a
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.1.2
  - wheel=0.37.1
  - widgetsnbextension=3.6.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - docker-pycreds==0.4.0
    - dysts==0.1
    - gitdb==4.0.9
    - gitpython==3.1.27
    - pathtools==0.1.2
    - promise==2.3
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - scipy==1.8.1
    - sentry-sdk==1.5.12
    - setproctitle==1.2.3
    - shortuuid==1.0.9
    - smmap==5.0.0
    - wandb==0.12.17

