name: chaos
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alsa-lib=1.2.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-timeout=4.0.1
  - attrs=21.4.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.4.26
  - cachetools=4.2.2
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=3.4.8
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - freetype=2.11.0
  - frozenlist=1.2.0
  - fsspec=2022.2.0
  - future=0.18.2
  - gettext=0.21.0
  - giflib=5.2.1
  - google-auth-oauthlib=0.4.4
  - grpcio=1.42.0
  - gst-plugins-base=1.20.1
  - gstreamer=1.20.1
  - icu=69.1
  - idna=3.3
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libclang=13.0.1
  - libdeflate=1.10
  - libedit=3.1.20210910
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libglib=2.70.2
  - libiconv=1.16
  - libllvm13=13.0.1
  - libnsl=2.0.0
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.2
  - libprotobuf=3.19.1
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvm-openmp=14.0.3
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - munkres=1.1.4
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - ninja=1.10.2
  - ninja-base=1.10.2
  - notebook=6.4.11
  - nspr=4.33
  - nss=3.74
  - numpy=1.21.5
  - numpy-base=1.21.5
  - oauthlib=3.2.0
  - openssl=1.1.1n
  - packaging=21.3
  - pandas=1.4.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - protobuf=3.19.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydeprecate=0.3.2
  - pygments=2.11.2
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python_abi=3.9
  - pytorch=1.10.2
  - pytorch-lightning=1.6.2
  - pytz=2021.3
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.12.9
  - qtconsole=5.3.0
  - qtpy=2.0.1
  - readline=8.1.2
  - requests=2.27.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - soupsieve=2.3.1
  - sqlite=3.38.2
  - stack_data=0.2.0
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.6.0
  - terminado=0.13.1
  - testpath=0.5.0
  - tk=8.6.12
  - torchmetrics=0.8.1
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - convertdate==2.4.0
    - cython==0.29.28
    - dysts==0.1
    - ephem==4.1.3
    - google-auth==1.35.0
    - hijri-converter==2.2.3
    - holidays==0.13
    - joblib==1.1.0
    - korean-lunar-calendar==0.2.1
    - lightgbm==3.3.2
    - llvmlite==0.38.0
    - nfoursid==1.0.0
    - numba==0.55.1
    - patsy==0.5.2
    - pymeeus==0.5.11
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - setuptools-git==1.2
    - statsforecast==0.5.4
    - statsmodels==0.13.2
    - threadpoolctl==3.1.0
    - u8darts==0.19.0
    - ujson==5.2.0
    - xarray==2022.3.0
