name: chaos
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy=1.22.4
  - torchmetrics=0.8.2
  - pip=22.1.1
  - pip:
    - brotlipy
    - jupyter
    - numpy
    - scikit-learn
    - tqdm
    - pytorch_lightning
    - seaborn
    - pandas
    - swifter
    - ipykernel
    - matplotlib
    - mysql
    - contextlib2==21.6.0
    - docker-pycreds==0.4.0
    - dysts==0.1
    - gitdb==4.0.9
    - gitpython==3.1.27
    - ml-collections==0.1.1
    - pathtools==0.1.2
    - promise==2.3
    - wandb==0.12.19
